### PR TITLE
Set pin and mandate backup keys for user

### PR DESCRIPTION
**Pull request by ajay-kays**

### CODE REVIEW

**Comment by ajay-kays** [comment]
@Entryist @mohamedsamara  Please review and let me know if anything needs to be corrected here.

**Comment by ajay-kays** [comment]
And how can i add link items to pull request and add reviewers cause i'm not able to find such option while creating the pull request.

**Comment by mohamedsamara** [comment]
@ajay-kays Thanks for the PR. I think there is and issue with "Export Keys"...it hangs and does not finish properly. Check out the screen record.

Also, can we make these changes:

* Enter Old Pin --To-- Enter Current Pin
* Choose PIN --To-- Enter New Pin

After changing pin
Show a confirm alert that says: “Are you sure you want to change you PIN?”

Cancel-> abort changes 
Once confirm -> The alert you added would say: “Your PIN has been updated. Please re-export your keys  using this new PIN.”

https://user-images.githubusercontent.com/45723974/147291661-a36c93af-a639-460a-b160-c49222c9fb5c.mov

**Comment by ajay-kays** [comment]
Ok, I'm on it

**Comment by ajay-kays** [comment]
@mohamedsamara  Thank you for pointing out those things. I've updated the PR, can you please review again.

**Comment by mohamedsamara** [comment]
@ajay-kays I put the screen recording of the issue with normal Export Keys. The set pin functionality broke the export keys flow. 

Also, the confirmation pin should be after they enter the new pin.
After changing pin
Show a confirm alert that says: “Are you sure you want to change you PIN?”

Can you please show the toast with black background instead and on TOP with same text of "Your PIN has been updated. Please re-export your keys using this new PIN."

https://user-images.githubusercontent.com/45723974/147505970-6168b83e-26a5-4413-b2cc-cacb4a83a396.mov

**Comment by ajay-kays** [comment]
@mohamedsamara 
The issue export not working or broken is purely on simulator. I've checked about it and i found few thread mentioning its bcoz of simulator. on real device it should work fine

**Comment by ajay-kays** [comment]
Meanwhile I'll get rid of the alert and show the confirmation alert when pin is changed

**Comment by ajay-kays** [comment]
@mohamedsamara  Can we connect on teams now ?

**Comment by mohamedsamara** [comment]
@ajay-kays Can you please change the Alert title message from "Notice" to "Confirm"? And this will be ready to merge after this change. Thanks!

**Comment by ajay-kays** [comment]
@mohamedsamara Ok, it's done. Please check again

**Comment by ajay-kays** [comment]
Solves https://github.com/getZION/app/issues/77

**Pull request merged**
